title = "Benevides' Blog"
baseURL = "https://mtrsk.github.io"
languageCode = "en-us"

pygmentsUseClasses = true
assetDir = "static"

[params]
  subtitle = "\"Writing is nothing more than a guided dream.\""
  math = true
  [params.author]
    name = "Marcos Benevides"

[outputs]
  section = ["HTML", "ATOM"]

[permalinks]
  blog = "/blog/:year/:slug/"
  notes = "/notes/:year/:slug/"


[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]

[outputFormats.Atom]
  name = "Atom"
  mediaType = "application/atom+xml"
  baseName = "atom"

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "rss"

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  ordered = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

