:PROPERTIES:
:ID:       0c082d02-4771-4860-8119-83b263c00ff3
:END:
#+title: History-of-Logic

Notes from the book "History of Logic: from Aristotle to Tarski".

* Intro

Roughly speaking, the development of logic in Europe has had three "golden
ages":
- Greek period, from around 350 to 200 BCE and included thinkers like:
  - Aristotle
  - Diodoru Cronus
  - Chrysippus
- High medieval period, from around 1100 to 1400
- Modern period, from around 1850 up to the present day

** The Greek period

From the beginning of the Greek golden period we get many anticipations of later
developments. From Aristotle we get a wonderfully worked out system of
"term-logic", known as the "syllogism", which was a precursor to the first-order
logic, or "predicate calculus", and which became easily the most influential
contribution in logic for two thousand years. From the Stoics we get the first
formulations of elements of propositional logic, with definitions of connectives
given via truth-values, but we also see many other interesting formulations of
logical problems, such as proposals for the nature of implication that are very
similar to some contemporary theories on subjunctive and indicative
conditionals. Much of the best work form the Stoic period, notably the work of
Chrysippus, has been lost to history, but we know indirectly that he wrote much
on logic generally, and specifi cally about paradoxes, including the Liar and
the Sorites. It was for a very long time thought that the Aristotelian and Stoic
conceptions of logic were at odds with one another, before their reconciliation
in the modern era under the umbrella of first-order logic. 

The fact that Aristotle’s achievement was so great actually had the unexpected
consequence of holding back logical progress. 

** The medieval period

While learning in the West declined, the study of logic was kept alive in the 
thriving Islamic world under the Abbasid Caliphate, reaching great heights of
sophistication with notable contributions from: 
- Al-Farabi
- Avicenna
- Averroes

From the start of the twelfth century onwards, Europe became increasingly
exposed to the Arabic world, and with this exposure came a rediscovery of the
ancient Greek texts on logic, especially those of Aristotle, along with the
benefit of the sophisticated Arabic commentaries. As these texts circulated
around Europe we find the beginning of our second golden age of logic, from
about 1100 to 1400, the high medieval or "scholastic" period, with notable
contributors including Peter Abelard, William of Sherwood, Peter of Spain,
William of Ockham and Paul of Venice. Curiously, during this period there was a
combination both innovative progress and reverence for ancient authority, most
particularly that of Aristotle. The progress came in the form of greater
understanding of quantification, reference and logical consequence, a more
intricate treatment of semantics, and developments in modal and temporal logic.

In the early decades of the sixteenth century, across northern Europe, we find
the introductory arts course being adapted to meet the requirements of an influx
of students from the professional classes. Within this arts course, with its
humanist predilection for Greek and Latin eloquence, and legal and ethical
instruction, there was an acknowledged need for some rigorous underpinning of
instruction in ‘clear thinking’. But the meticulous introduction to formal logic
and semantic theory provided by the scholastic programme came to look
increasingly unsuitable for this purpose.
Lisa Jardine 1982 : 805 

** The birth of Calculus

While the study of pure logic may have declined in the early scientific period,
there were a great many advances in mathematics, in particular in algebra and
geometry. By the end of the sixteenth century European mathematicians had
recovered many of the works from antiquity that had been lost, and largely
improved upon the Arabic algebraic developments. This period of mathematical
progress arguably culminated with the creation of the infinitesimal calculus of
Leibniz (1646–1716) and Newton (1642–1727). Leibniz himself was an outstanding
mind who worked in many fields and, against the intellectual tide of his day, he
conducted a solitary programme of innovative research in formal logic. Although
the main body of Leibniz’s works on logic remained relatively unknown until the
turn of the twentieth century, in retrospect he is hugely significant for
articulating a completely new vision of the subject – one that stressed the use
of the recently developed mathematical and algebraic methods.

Leibniz’s motivations for pursuing an algebraic treatment of logic were deeply
rooted in his philosophical views. He conceived of a mathematically
reconstructed logic as a medium that would refl ect the nature of thought more
faithfully than the comparatively clumsy linguistic approach of the medieval
logicians. The idea was that this new logic, being symbolic rather than
linguistic, would actually improve the way that we think, by laying out the real
elements of thought with perfect clarity, and would therefore be a crucial key
in advancing science generally. In his ambition, Leibniz saw the possibility for
a universal language of thought based on logic; a lingua philosophica (or
‘philosophical language’), which is something that would be recognizable to any
student of analytic philosophy today. Despite the details of Leibniz’s logical
innovations remaining largely out of sight in the Royal Library of Hanover until
the turn of the twentieth century, the general character of his vision managed
to exert an infl uence on a number of early pioneers in the modern age of
logic. For instance, Leibniz’s ideal of a perfect language of thought heavily
infl uenced two of the most important logicians of the early modern period;
George Boole (1815–1864) and Gottlob Frege. This influence is reflected in the
titles of their best known works on logic – Boole’s 1854 work "The Laws of
Thought" and Frege’s 1879 work "Begriffsschrift" (which means ‘concept-
script’). Although Boole and Frege diff ered signifi cantly in their approaches,
both were trying to realize the mathematical vision of logic that Leibniz had
envisaged.

** The modern era

- George Boole: Inspired by Aristotle and Leibniz, Boole managed to encode
  logical statements in a algebraic manner.
- Charles Sanders Pierce:   Further developing on Boole's approach, adding many
  contributions and taking the bold move to abandon Aristotle's Logic. Pierce
  also tried to work with what today looks like Temporal and Modal Logics, and
  helped develop and introduce the modern version of quantifiers.
- Gottlob Frege: Alongside Pierce, Frege independentely helped introduce the
  idea of universal quantifiers. Frege work is also famous for being what we
  would today call /Predicate Calculus/ in the modern sense, since it contains a
  formal language with quantifiers, logical connectives and predicates
  (including unary and relational ones), together with a set of Axioms and one
  law of inference (/Modus Pones/).
- Russel & Whitehead:
- David Hilbert:
- Kurt Gödel:
- Alfred Tarski: Tarski's landmark paper "On the concept of Truth in Formalized
  Languages" contains a definition of the satisfaction relation.

Aristotelian quantifier phrases take two predicates as arguments: they have the
form ‘All A are B’, ‘Some A is B’, ‘No A is B’ or ‘Not all A are B’. Fregean or
Peircian quantifi ers are unary and introduce a bound variable : a variable
standing

One of the fundamental insights of the algebraic approach to logic was that
logical symbols are subject to interpretation, as symbols in algebra are (for
example, the geometric interpretation of complex numbers). Th is leads naturally
to the idea of a model : an interpretation of the vocabulary of a logical system
which satisfies its axioms. We therefore come to the notion of a Boolean
algebra: any model of Boole’s axioms of logic. Such algebras consist of a set of
atoms, the elements of the algebra; distinguished elements 0 and 1; and
conjunction (intersection or multiplication), disjunction (union or addition)
and complementation (negation or subtraction) operations on the set of
elements. The study of Boolean algebras was begun by Marshall Stone, who proved
a number of important results, including the representation theorem that bears
his name: every Boolean algebra is isomorphic to (that is, has the same
structure as) a Boolean algebra of sets.

We can trace the birth of model theory to Löwenheim’s paper "Über Möglichkeiten
im Relativkalkül". Working within Schröder’s version of the calculus of
relations, Löwenheim showed that if a first-order sentence has a model, then it
has a countable model. Th e Norwegian mathematician Thoralf Skolem improved
Löwenheim’s proof in a paper of 1920, and in doing so generalized the result
from single sentences to (possibly infi nite) sets of sentences. The result is
important because it shows that first-order logic is not, in general, able to
fix the cardinalities of its models: there can, for example, be models of the
theory of real numbers which are countable, or models of set theory where sets
that the theory holds to be uncountable are actually (from the external,
model-theoretic perspective) countable. The completeness theorem for first-order
logic, later proved by Gödel in his 1929 PhD thesis, is an easy corollary of
Skolem’s work from the early 1920s, but this was not understood until later.

