:PROPERTIES:
:ID:       bcd04f60-0a4c-4213-90f7-139c0ddf5bef
:END:
#+title: Erlang Shell
#+HUGO_CATEGORIES: "Functional Programming"
#+HUGO_TAGS: "Erlang"

Some features of the [[id:de7d0e94-618f-4982-b3e5-8806d88cad5d][Erlang]] shell.

* Basics
** Compiling and Running "Hello World" in the Shell
#+BEGIN_SRC erlang
  -module(hello).
  -export([start/0]).
  
  start() ->
      io:format("Hello world~n").
#+END_SRC

Running the ~hello.erl~ program in the erlang shell.

#+BEGIN_SRC shell
  $ erl                          
  Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit:ns]

  Eshell V14.2.5 (press Ctrl+G to abort, type help(). for help)
  1> c(hello).
  {ok,hello}
  2> hello:start().
  Hello world
  ok
#+END_SRC

*** Compiling Outside the Erlang Shell

#+BEGIN_SRC shell
  $ erlc hello.erl
  $ erl -noshell -s hello start -s init stop
#+END_SRC

#+BEGIN_QUOTE
~erlc~ evokes the Erlang compiler from the command line. The compiler compiles the code in ~hello.erl~ and produces an object code file called ~hello.beam~.

The ~erl -noshell~ command loads the module ~hello~ and evaluates the function
~hello:start()~. After this, it evaluates the expression ~init:stop()~, which
terminates the Erlang session. [cite:@armstrong2013 p.14]
#+END_QUOTE

* Commands
** Seeing Your Bound Variables

~b()~ shows all bound variables in the current erlang shell.

#+BEGIN_SRC shell
    > b().
    N = 1
    Number = 5
#+END_SRC

** Clearing Bound Variables in the Shell

#+BEGIN_SRC shell
  > f(N).
  > f().
#+END_SRC

* Modifying the Development Environment

You can find the value of the current load path by starting an Erlang shell
and giving the command ~code:get_path()~. The two most common functions that we
use to manipulate the load path are as follows:

#+begin_src erlang
% Add a new directory to the start of the load path.
-spec code:add_patha(Dir) => true | {error, bad_directory}
% Add a new directory to the end of the load path.
-spec code:add_pathz(Dir) => true | {error, bad_directory}
#+end_src

Alternatively, you can start Erlang with a command like this:
#+begin_src shell
$ erl -pa Dir1 -pa Dir2 ... -pz DirK1 -pz DirK2
#+end_src

#+print_bibliography:
