:PROPERTIES:
:ID:       1daea4ea-40bc-406d-8d03-906c7f9ec343
:END:
#+TITLE: Programming Erlang
#+ROAM_TAGS: "erlang"

* Part I: Why Erlang?

** Introducing Concurrency

*** Modeling Concurrency

~spawn~ is an Erlang primitive that creates a concurrent process and returns a
process identifier (PID) that can used to interact with the newly created process:

#+BEGIN_SRC erlang
spawn(ModName, FuncName, [Arg1, Arg2, ..., ArgN])
#+END_SRC

The syntax ~Pid ! Msg~ means "send the message ~Msg~ to the process ~Pid~". And for
~Pid~ to process a message we need to pattern match:

#+BEGIN_SRC erlang
receive
    {From, Message} ->
        ...
end
#+END_SRC

*** Benefits of Concurrency

+ Performance
+ Scalability
+ Fault Tolerance
+ Clarity

** A Whirlwind Tour of Erlang
*** Syntax of Variables and Atoms
#+BEGIN_QUOTE
Note that Erlang variables start with uppercase characters. So, ~X~, ~This~, and
~A_long_name~ are all variables. Names beginning with lowercase letters—for example,
~monday~ or ~friday~ are not variables but are symbolic constants called 
atoms.
#+END_QUOTE

*** Compiling and Running "Hello World" in the Shell
#+BEGIN_SRC erlang
  -module(hello).
  -export([start/0]).
  
  start() ->
      io:format("Hello world~n").
#+END_SRC

Running the ~hello.erl~ program in the erlang shell.

#+BEGIN_SRC shell
  $ erl                          
  Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit:ns]

  Eshell V14.2.5 (press Ctrl+G to abort, type help(). for help)
  1> c(hello).
  {ok,hello}
  2> hello:start().
  Hello world
  ok
#+END_SRC

*** Compiling Outside the Erlang Shell

#+BEGIN_SRC shell
  $ erlc hello.erl
  $ erl -noshell -s hello start -s init stop
#+END_SRC

#+BEGIN_QUOTE
~erlc~ evokes the Erlang compiler from the command line. The compiler compiles the code in ~hello.erl~ and produces an object code file called ~hello.beam~.

The ~erl -noshell~ command loads the module ~hello~ and evaluates the function
~hello:start()~. After this, it evaluates the expression ~init:stop()~, which
terminates the Erlang session.
#+END_QUOTE

* Part II: Sequential Programming

** Basic Concepts
*** Variables
+ Erlang Variables Do Not Vary
+ The scope of a variable is the lexical unit in which it is defined.
+ Variables acquire values as the result of a successful pattern matching
  operation (~=~).

*** Floating-Point Numbers
+ When you divide two integers with ~/~, the result is automatically converted to a floating-point number.
+ Integer division is handled by ~div~ and ~rem~.

*** Atoms
+ In Erlang, atoms are used to represent constant values.
+ Atoms are also global, and this is achieved without the use of macro
  definitions or include files.

*** Tuples
+ Represents a collection of elements (of any type) that are grouped together.
+ A tuple whose first element is an atom is called a ~tagged~ tuple, i.e., ~{book,
  "The Aleph"}~.

#+BEGIN_QUOTE
Tuples are created automatically when we declare them and are destroyed when
they can no longer be used. Erlang uses a garbage collector to reclaim all
unused memory, so we don’t have to worry about memory allocation.
#+END_QUOTE

You can also pattern match tuples by using free variables:
#+BEGIN_SRC shell
  1> Point = {point, 10, 45}.
  {point,10,45}
  2> {point, X, Y} = Point.
  {point,10,45}
  3> X.
  10
  4> Y.
  45
#+END_SRC

*** Lists

+ A list is a compound data type with a variable number of terms: ~[Term1,...,TermN]~.
+ One can add or iterate over lists with the ~cons~ operator ~|~, which breaks a
  list into ~H|T~ (~head~ and ~tail~),

*** Strings
#+BEGIN_QUOTE
Strictly speaking, there are no strings in Erlang. To represent a string in
Erlang, we can choose between representing the string as a list of integers or
as a binary. When a string is represented as a list of integers, each element in
the list represents a Unicode codepoint.
#+END_QUOTE

To print a unicode string one must use the "t" modifier applied to the "s"
control character in a formatting string, it accepts all Unicode codepoints and
expect binaries to be in UTF-8:

#+BEGIN_SRC shell
  1> X = "a\x{221e}b".
  [97,8734,98]
  2> io:format("~ts~n",[X]).
  a∞b
  ok
#+END_SRC

** Modules and Functions

*** Modules Are Where We Store Code

#+BEGIN_SRC erlang
  -module(geometry).
  -export([area/1]).

  area({rectangle, Width, Height}) -> Width * Height;
  area({circle, Radius}) -> 3.14159 * Radius * Radius;
  area({square, Side}) -> Side * Side.
#+END_SRC

*** Funs: The Basic Unit of Abstraction

~Funs~ are function closures. ~Funs~ are created by expressions of the form: ~fun(...) -> ... end~.

*** Defining Your Own Control Abstractions
If we want additional control structures, we can make our own. Erlang has no for loop, so let’s make one:
#+BEGIN_SRC erlang
  for(Max, Max, F) -> [F(Max)];
  for(I, Max, F) -> [F(I)|for(I+1, Max, F)].
#+END_SRC

*** List Comprehensions

#+BEGIN_SRC shell
  1> L = [1,2,3,4,5,6,7].
  [1,2,3,4,5,6,7]
  2> [ 2*X || X <- L ].
  [2,4,6,8,10,12,14]
  3> 
#+END_SRC

#+BEGIN_QUOTE
The most general form of a list comprehension is an expression of the following
form: ~[X || Qualifier1, Qualifier2, ...]~, where ~X~ is an arbitrary expression,
and each qualifier is either a generator, a bitstring generator, or a filter.

+ Generators are written as ~Pattern <- ListExpr~ where ~ListExpr~ must be an expression that evaluates to a list of terms.
+ Bitstring generators are written as ~BitStringPattern <= BitStringExpr~ where ~BitStringExpr~ must be an expression that evaluates to a bitstring.
+ Filters are either predicates or boolean expressions.
#+END_QUOTE

*** case and if Expressions

#+BEGIN_SRC erlang
  case Expression of
    Pattern1 [when Guard1] -> Expr_seq1;
    Pattern2 [when Guard2] -> Expr_seq2;
    ...
  end

  if
    Guard1 -> Expr_seq1;
    Guard2 -> Expr_seq2;
    ...
  end
#+END_SRC
