name: Build

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pr-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Build website
        run: nix develop .#ci -c just ci-build
